- name: copy the catalogue service 
  ansible.builtin.copy:
    src: catalogue.service
    dest: /etc/systemd/system/catalogue.service

- name: Reload the daemon
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start and enable catalogue service
  ansible.builtin.service:
    name: catalogue
    state: restarted
    enabled: yes
