- name: Installng cart
  hosts: all
  become: true
  become_method: sudo
  tasks:
    - name: Disable and Enable nodejs
      ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

    - name: Install nodejs
      ansible.builtin.dnf:
        name: nodejs:18
        state: present

    - name: create user
      ansible.builtin.user:
        name: roboshop
        state: present

    - name: create an app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: Download the app code
      ansible.builtin.get_url:
        url: https://roboshop-builds.s3.amazonaws.com/cart.zip
        dest: /tmp

    - name: unzip the app code
      ansible.builtin.unarchive:
        src: /tmp/cart.zip
        dest: /app
        remote_src: yes

    - name: Download the dependencies
      ansible.builtin.command: npm install
      args:
        chdir: /app

    - name: copy the cart service
      ansible.builtin.copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: Re-load the daemon
      ansible.builtin.systemd_service:
        daemon_reload: true

    - name: Start and Enable the cart service
      ansible.builtin.service:
        name: cart
        state: started
        enabled: yes
