- name: Installing and running Redis server
  hosts: all
  become: true
  become_methos: sudo
  tasks:
    - name: Install remi release
      ansible.builtin.dnf:
        name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
        state: present

    - name: Enable redis:6.2 from package
      ansible.builtin.command: dnf module enable redis:remi-6.2 -y

    - name: Install redis
      ansible.builtin.dnf:
        name: redis
        state: present

    - name: Replace localhost and allow remote connections
      ansible.builtin.replace:
        path: /etc/redis.conf
        regexp: '127.0.0.1'
        replace: '0.0.0.0'

    - name: Start and Enable Redis Service
      ansible.builtin.service:
        name: redis
        state: started
        enabled: yes
